# Generated by Django 5.0.3 on 2024-03-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayaw_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='booking',
        ),
        migrations.DeleteModel(
            name='cottages',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='gcash',
        ),
        migrations.DeleteModel(
            name='Guest_list',
        ),
        migrations.DeleteModel(
            name='information',
        ),
        migrations.DeleteModel(
            name='message_storage_1',
        ),
        migrations.DeleteModel(
            name='message_storage_2',
        ),
        migrations.DeleteModel(
            name='message_storage_3',
        ),
        migrations.DeleteModel(
            name='nationality',
        ),
        migrations.DeleteModel(
            name='paid',
        ),
        migrations.DeleteModel(
            name='paymaya',
        ),
        migrations.DeleteModel(
            name='rooms',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
