# Generated by Django 5.0.3 on 2024-03-14 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayaw_app', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
