# Generated by Django 5.0.3 on 2024-03-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayaw_app', '0006_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='changeschedule_reason',
            field=models.TextField(null=True),
        ),
    ]
