# Generated by Django 5.0.3 on 2024-03-21 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayaw_app', '0007_booking_changeschedule_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='is_cancel',
            new_name='change_schedule',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='is_cancellation_approve',
            new_name='changeschedule_approve',
        ),
    ]
