# Generated by Django 5.0.3 on 2024-05-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayaw_app', '0009_alter_booking_change_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='change_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=500)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
