# Generated by Django 5.0.3 on 2024-05-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayaw_app', '0010_change_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='change_schedule',
            name='code',
            field=models.TextField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='change_schedule',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='change_schedule',
            name='reason',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='change_schedule',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
